### Json dictionaries

In [ ]:
import json
dic = {
    1:1,
    2:2
}

print(dic)

with open("args.json", "w") as outfile:
    json.dump(dic, outfile)

f = open("args.json", "r")
args = json.loads(f.read())
f.close()

print(args)

### Multichannel thresholds

In [24]:
threshold = [0.5, 0.7]
all(val>0 and val<1 for val in threshold)


True

In [25]:
import numpy as np
ones = np.ones((100,2))
ones.shape
num_events = 2

In [27]:
for i in range(num_events):
    ones[:,i] = ones[:,i]*threshold[i]

### Linspace

In [43]:
import numpy as np
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])